servers:
  - hostname: ip-10-31-4-84.ap-south-1.compute.internal
    apache:
      - instance: ip-10-31-4-84.ap-south-1.compute.internal
    tomcat:
      - instance: 1111
    oracle:
      - sid: localhost:1521/xe

# ARCHITECTURE (Flow Mapping)
architecture:
  - flow_id: flow_1
    web:
      hostname: ip-10-31-4-84.ap-south-1.compute.internal
      instance: ip-10-31-4-84.ap-south-1.compute.internal_80
    app:
      hostname: ip-10-31-4-84.ap-south-1.compute.internal
      instance: 1111
    db:
      hostname: ip-10-31-4-84.ap-south-1.compute.internal
      sid: localhost:1521/xe
