from pathlib import Path

# ===== InfluxDB config =====
INFLUX_HOST = "10.31.4.155"
INFLUX_PORT = 8086
INFLUX_USERNAME = "admin"
INFLUX_PASSWORD = "admin"
INFLUX_DB = "macaDB"

# START_TIME = "2026-05-29T08:36:20Z"
# END_TIME = "2026-05-29T11:18:52Z"

# ===== THRESHOLDS =====
CPU_HIGH_THRESHOLD = 85
MEMORY_HIGH_THRESHOLD = 80
LATENCY_HIGH_THRESHOLD = 1000
ERROR_RATE_THRESHOLD = 0.05
CORRELATION_THRESHOLD = 0.7
RPS_HIGH_THRESHOLD = 200
MIN_SUSTAINED_DURATION = 5
TREND_THRESHOLD = 0.1
MIN_DURATION = 3
ANOMALIES_THRESHOLD = 3
CPU_RT_CORR_THRESHOLD = 0.7
MEMORY_LATENCY_CORR_THRESHOLD = 0.7
LATENCY_CRITICAL = 1500
ERROR_RATE_THRESHOLD = 0.05   # 5%
ERROR_CRITICAL_THRESHOLD = 0.1  # 10%

# ===== JMeter Results Path =====
JMeterResultPath = Path('performance_analyzer/JMeterResults/aggregate/')

# ===== Apache THRESHOLDS =====

APACHE_LATENCY_THRESHOLD = 1000
APACHE_LATENCY_CRITICAL = 1500
APACHE_ERROR_THRESHOLD = 0.05
APACHE_WORKER_UTIL_THRESHOLD = 80


# ===== TOMCAT THRESHOLDS =====

TOMCAT_GC_TIME_THRESHOLD = 500
TOMCAT_GC_COUNT_THRESHOLD = 10
TOMCAT_HEAP_USAGE_THRESHOLD = 85
TOMCAT_THREAD_UTIL_THRESHOLD = 90
TOMCAT_DB_CONN_THRESHOLD = 80

# ===== ORACLE THRESHOLDS =====
DB_EXEC_TIME_THRESHOLD = 200  # ms
DB_WAIT_TIME_THRESHOLD = 100
DB_CALLS_THRESHOLD = 1000
DB_MEMORY_THRESHOLD = 80
